version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      semver-patch-days: 7
      semver-minor-days: 7
      semver-major-days: 14
    groups:
      gomod-minor-patch:
        update-types:
          - "minor"
          - "patch"
      gomod-major:
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      semver-patch-days: 7
      semver-minor-days: 7
      semver-major-days: 14
    groups:
      github-actions:
        patterns:
          - "*"
