name: Nix build

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Nix build
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Nix build
        run: nix build .#default --print-build-logs

      - name: Smoke test
        run: ./result/bin/bitbottle --version
